[package]
name = "lerni"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Lerni content framework"
repository = "https://github.com/lerni-edu/lerni"
include = ["src/**/*.rs", "examples/**/*.rs"]

[dependencies]
derive_more = "0.99.17"
getrandom = { version = "0.2.8", features = ["js"] }
gloo-events = "0.1.2"
gloo-utils = "0.1.6"
rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }
yew = { version = "0.20.0", features = ["csr"] }
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "SvgElement",
    "TextMetrics",
]

[[example]]
name = "blur"
crate-type = ["cdylib"]

[[example]]
name = "buttons"
crate-type = ["cdylib"]

[[example]]
name = "grid"
crate-type = ["cdylib"]

[[example]]
name = "hello_world"
crate-type = ["cdylib"]

[[example]]
name = "pointer"
crate-type = ["cdylib"]

[[example]]
name = "rows_cols"
crate-type = ["cdylib"]

[[example]]
name = "svg"
crate-type = ["cdylib"]

[[example]]
name = "text"
crate-type = ["cdylib"]
