[package]
name = "lerni"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Lerni content framework"
repository = "https://github.com/lerni-edu/lerni"
include = ["src/**/*.rs", "examples/**/*.rs"]

[dependencies]
derive_more = "0.99.17"
gloo-events = "0.1.2"
yew = "0.20.0"
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
version = "0.3.60"
features = ["SvgElement"]

[[example]]
name = "buttons"
crate-type = ["cdylib"]

[[example]]
name = "grid"
crate-type = ["cdylib"]

[[example]]
name = "hello_world"
crate-type = ["cdylib"]

[[example]]
name = "pointer"
crate-type = ["cdylib"]
