[package]
name = "lerni"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Lerni content framework"
include = ["src/**/*.rs"]

[dependencies]
yew = "0.19.3"
wasm-bindgen = "0.2.83"

[[example]]
name = "hello_world"
crate-type = ["cdylib"]
